{"text": "2020-12-29T09:41:21.435157+0300 INFO\n", "record": {"elapsed": {"repr": "0:00:01.560327", "seconds": 1.560327}, "exception": null, "extra": {}, "file": {"name": "main.py", "path": "main.py"}, "function": "process_nifi_connectors", "level": {"icon": "\u2139\ufe0f", "name": "INFO", "no": 20}, "line": 172, "message": "{\"id\": \"d40520fd-3f4a-157c-25a2-bb44fe03b212\", \"name\": \"Power Bi Connector (Unicef Philippines) \", \"parentGroupId\": \"50bce21f-0171-1000-d983-307ac9814c13\", \"runningCount\": 0, \"stoppedCount\": 71, \"invalidCount\": 5, \"disabledCount\": 0, \"activeRemotePortCount\": 0, \"inactiveRemotePortCount\": 0, \"upToDateCount\": 0, \"locallyModifiedCount\": 0, \"staleCount\": 0, \"locallyModifiedAndStaleCount\": 0, \"syncFailureCount\": 0, \"localInputPortCount\": 0, \"localOutputPortCount\": 0, \"publicInputPortCount\": 0, \"publicOutputPortCount\": 0, \"inputPortCount\": 0, \"outputPortCount\": 0, \"statsLastRefreshed\": \"06:41:21 UTC\", \"versionedFlowState\": \"LOCALLY_MODIFIED\", \"flowFilesIn\": 0, \"bytesIn\": 0, \"input\": \"0 (0 bytes)\", \"flowFilesQueued\": 0, \"bytesQueued\": 0, \"queued\": \"0 (0 bytes)\", \"queuedCount\": \"0\", \"queuedSize\": \"0 bytes\", \"bytesRead\": 0, \"read\": \"0 bytes\", \"bytesWritten\": 0, \"written\": \"0 bytes\", \"flowFilesOut\": 0, \"bytesOut\": 0, \"output\": \"0 (0 bytes)\", \"flowFilesTransferred\": 0, \"bytesTransferred\": 0, \"transferred\": \"0 (0 bytes)\", \"bytesReceived\": 0, \"flowFilesReceived\": 0, \"received\": \"0 (0 bytes)\", \"bytesSent\": 0, \"flowFilesSent\": 0, \"sent\": \"0 (0 bytes)\", \"activeThreadCount\": 0, \"terminatedThreadCount\": 0, \"bulletinCount\": 0, \"errorCount\": 0, \"bulletins\": []}", "module": "main", "name": "__main__", "process": {"id": 18460, "name": "MainProcess"}, "thread": {"id": 140163409274688, "name": "MainThread"}, "time": {"repr": "2020-12-29 09:41:21.435157+03:00", "timestamp": 1609224081.435157}}}
{"text": "2020-12-29T09:41:21.438118+0300 INFO\n", "record": {"elapsed": {"repr": "0:00:01.563288", "seconds": 1.563288}, "exception": null, "extra": {}, "file": {"name": "main.py", "path": "main.py"}, "function": "process_nifi_connectors", "level": {"icon": "\u2139\ufe0f", "name": "INFO", "no": 20}, "line": 172, "message": "{\"id\": \"01711010-8d91-13fa-0065-8fa509877ae4\", \"name\": \"Unicef Rosa\", \"parentGroupId\": \"50bce21f-0171-1000-d983-307ac9814c13\", \"runningCount\": 160, \"stoppedCount\": 0, \"invalidCount\": 10, \"disabledCount\": 0, \"activeRemotePortCount\": 0, \"inactiveRemotePortCount\": 0, \"upToDateCount\": 0, \"locallyModifiedCount\": 0, \"staleCount\": 1, \"locallyModifiedAndStaleCount\": 0, \"syncFailureCount\": 0, \"localInputPortCount\": 0, \"localOutputPortCount\": 0, \"publicInputPortCount\": 0, \"publicOutputPortCount\": 0, \"inputPortCount\": 0, \"outputPortCount\": 0, \"statsLastRefreshed\": \"06:41:21 UTC\", \"versionedFlowState\": \"LOCALLY_MODIFIED\", \"flowFilesIn\": 0, \"bytesIn\": 0, \"input\": \"0 (0 bytes)\", \"flowFilesQueued\": 0, \"bytesQueued\": 0, \"queued\": \"0 (0 bytes)\", \"queuedCount\": \"0\", \"queuedSize\": \"0 bytes\", \"bytesRead\": 0, \"read\": \"0 bytes\", \"bytesWritten\": 0, \"written\": \"0 bytes\", \"flowFilesOut\": 0, \"bytesOut\": 0, \"output\": \"0 (0 bytes)\", \"flowFilesTransferred\": 0, \"bytesTransferred\": 0, \"transferred\": \"0 (0 bytes)\", \"bytesReceived\": 0, \"flowFilesReceived\": 0, \"received\": \"0 (0 bytes)\", \"bytesSent\": 0, \"flowFilesSent\": 0, \"sent\": \"0 (0 bytes)\", \"activeThreadCount\": 3, \"terminatedThreadCount\": 0, \"bulletinCount\": 5, \"errorCount\": 5, \"bulletins\": [{\"id\": 64920, \"category\": \"Log Message\", \"groupId\": \"4f68617e-e434-3774-cea6-47ce0a631fbe\", \"sourceId\": \"d135e6be-1f63-3651-ca5f-baf98d744a4d\", \"sourceName\": \"Add Labels\", \"level\": \"ERROR\", \"message\": \"ExecuteScript[id=d135e6be-1f63-3651-ca5f-baf98d744a4d] Failed to properly initialize Processor. If still scheduled to run, NiFi will attempt to initialize and run the Processor again after the 'Administrative Yield Duration' has elapsed. Failure is due to Traceback (most recent call last):\\n  File \\\"/opt/nifi/nifi-current/work/nar/extensions/nifi-scripting-nar-1.11.4.nar-unpacked/NAR-INF/bundled-dependencies/jython-shaded-2.7.1.1.jar/Lib/site.py\\\", line 69, in <module>\\nIOError: java.nio.channels.ClosedByInterruptException\\n: Traceback (most recent call last):\\n  File \\\"/opt/nifi/nifi-current/work/nar/extensions/nifi-scripting-nar-1.11.4.nar-unpacked/NAR-INF/bundled-dependencies/jython-shaded-2.7.1.1.jar/Lib/site.py\\\", line 69, in <module>\\nIOError: java.nio.channels.ClosedByInterruptException\\n\", \"timestamp\": \"06:40:42 UTC\"}, {\"id\": 64917, \"category\": \"Log Message\", \"groupId\": \"4f68617e-e434-3774-cea6-47ce0a631fbe\", \"sourceId\": \"050cb960-16e7-3e13-9c9a-ba003887408b\", \"sourceName\": \"Format Geotypes\", \"level\": \"ERROR\", \"message\": \"ExecuteScript[id=050cb960-16e7-3e13-9c9a-ba003887408b] Failed to properly initialize Processor. If still scheduled to run, NiFi will attempt to initialize and run the Processor again after the 'Administrative Yield Duration' has elapsed. Failure is due to Traceback (most recent call last):\\n  File \\\"/opt/nifi/nifi-current/work/nar/extensions/nifi-scripting-nar-1.11.4.nar-unpacked/NAR-INF/bundled-dependencies/jython-shaded-2.7.1.1.jar/Lib/site.py\\\", line 585, in <module>\\n  File \\\"/opt/nifi/nifi-current/work/nar/extensions/nifi-scripting-nar-1.11.4.nar-unpacked/NAR-INF/bundled-dependencies/jython-shaded-2.7.1.1.jar/Lib/site.py\\\", line 567, in main\\n  File \\\"/opt/nifi/nifi-current/work/nar/extensions/nifi-scripting-nar-1.11.4.nar-unpacked/NAR-INF/bundled-dependencies/jython-shaded-2.7.1.1.jar/Lib/site.py\\\", line 300, in addusersitepackages\\n  File \\\"/opt/nifi/nifi-current/work/nar/extensions/nifi-scripting-nar-1.11.4.nar-unpacked/NAR-INF/bundled-dependencies/jython-shaded-2.7.1.1.jar/Lib/site.py\\\", line 275, in getusersitepackages\\n  File \\\"/opt/nifi/nifi-current/work/nar/extensions/nifi-scripting-nar-1.11.4.nar-unpacked/NAR-INF/bundled-dependencies/jython-shaded-2.7.1.1.jar/Lib/site.py\\\", line 265, in getuserbase\\n  File \\\"/opt/nifi/nifi-current/work/nar/extensions/nifi-scripting-nar-1.11.4.nar-unpacked/NAR-INF/bundled-dependencies/jython-shaded-2.7.1.1.jar/Lib/sysconfig.py\\\", line 565, in get_config_var\\n  File \\\"/opt/nifi/nifi-current/work/nar/extensions/nifi-scripting-nar-1.11.4.nar-unpacked/NAR-INF/bundled-dependencies/jython-shaded-2.7.1.1.jar/Lib/sysconfig.py\\\", line 441, in get_config_vars\\n  File \\\"/opt/nifi/nifi-current/work/nar/extensions/nifi-scripting-nar-1.11.4.nar-unpacked/NAR-INF/bundled-dependencies/jython-shaded-2.7.1.1.jar/Lib/re.py\\\", line 105, in <module>\\n  File \\\"/opt/nifi/nifi-current/work/nar/extensions/nifi-scripting-nar-1.11.4.nar-unpacked/NAR-INF/bundled-dependencies/jython-shaded-2.7.1.1.jar/Lib/sre_compile.py\\\", line 483, in <module>\\n  File \\\"/opt/nifi/nifi-current/work/nar/extensions/nifi-scripting-nar-1.11.4.nar-unpacked/NAR-INF/bundled-dependencies/jython-shaded-2.7.1.1.jar/Lib/encodings/__init__.py\\\", line 32, in <module>\\n  File \\\"/opt/nifi/nifi-current/work/nar/extensions/nifi-scripting-nar-1.11.4.nar-unpacked/NAR-INF/bundled-dependencies/jython-shaded-2.7.1.1.jar/Lib/encodings/_java.py\\\", line 10, in <module>\\nIOError: java.nio.channels.ClosedByInterruptException\\n: Traceback (most recent call last):\\n  File \\\"/opt/nifi/nifi-current/work/nar/extensions/nifi-scripting-nar-1.11.4.nar-unpacked/NAR-INF/bundled-dependencies/jython-shaded-2.7.1.1.jar/Lib/site.py\\\", line 585, in <module>\\n  File \\\"/opt/nifi/nifi-current/work/nar/extensions/nifi-scripting-nar-1.11.4.nar-unpacked/NAR-INF/bundled-dependencies/jython-shaded-2.7.1.1.jar/Lib/site.py\\\", line 567, in main\\n  File \\\"/opt/nifi/nifi-current/work/nar/extensions/nifi-scripting-nar-1.11.4.nar-unpacked/NAR-INF/bundled-dependencies/jython-shaded-2.7.1.1.jar/Lib/site.py\\\", line 300, in addusersitepackages\\n  File \\\"/opt/nifi/nifi-current/work/nar/extensions/nifi-scripting-nar-1.11.4.nar-unpacked/NAR-INF/bundled-dependencies/jython-shaded-2.7.1.1.jar/Lib/site.py\\\", line 275, in getusersitepackages\\n  File \\\"/opt/nifi/nifi-current/work/nar/extensions/nifi-scripting-nar-1.11.4.nar-unpacked/NAR-INF/bundled-dependencies/jython-shaded-2.7.1.1.jar/Lib/site.py\\\", line 265, in getuserbase\\n  File \\\"/opt/nifi/nifi-current/work/nar/extensions/nifi-scripting-nar-1.11.4.nar-unpacked/NAR-INF/bundled-dependencies/jython-shaded-2.7.1.1.jar/Lib/sysconfig.py\\\", line 565, in get_config_var\\n  File \\\"/opt/nifi/nifi-current/work/nar/extensions/nifi-scripting-nar-1.11.4.nar-unpacked/NAR-INF/bundled-dependencies/jython-shaded-2.7.1.1.jar/Lib/sysconfig.py\\\", line 441, in get_config_vars\\n  File \\\"/opt/nifi/nifi-current/work/nar/extensions/nifi-scripting-nar-1.11.4.nar-unpacked/NAR-INF/bundled-dependencies/jython-shaded-2.7.1.1.jar/Lib/re.py\\\", line 105, in <module>\\n  File \\\"/opt/nifi/nifi-current/work/nar/extensions/nifi-scripting-nar-1.11.4.nar-unpacked/NAR-INF/bundled-dependencies/jython-shaded-2.7.1.1.jar/Lib/sre_compile.py\\\", line 483, in <module>\\n  File \\\"/opt/nifi/nifi-current/work/nar/extensions/nifi-scripting-nar-1.11.4.nar-unpacked/NAR-INF/bundled-dependencies/jython-shaded-2.7.1.1.jar/Lib/encodings/__init__.py\\\", line 32, in <module>\\n  File \\\"/opt/nifi/nifi-current/work/nar/extensions/nifi-scripting-nar-1.11.4.nar-unpacked/NAR-INF/bundled-dependencies/jython-shaded-2.7.1.1.jar/Lib/encodings/_java.py\\\", line 10, in <module>\\nIOError: java.nio.channels.ClosedByInterruptException\\n\", \"timestamp\": \"06:40:41 UTC\"}, {\"id\": 64884, \"category\": \"Log Message\", \"groupId\": \"4f68617e-e434-3774-cea6-47ce0a631fbe\", \"sourceId\": \"d6d051c0-1d07-3a7a-9bc5-0c42b47a60e8\", \"sourceName\": \"Flatten JSON\", \"level\": \"ERROR\", \"message\": \"ExecuteScript[id=d6d051c0-1d07-3a7a-9bc5-0c42b47a60e8] Failed to properly initialize Processor. If still scheduled to run, NiFi will attempt to initialize and run the Processor again after the 'Administrative Yield Duration' has elapsed. Failure is due to Traceback (most recent call last):\\n  File \\\"/opt/nifi/nifi-current/work/nar/extensions/nifi-scripting-nar-1.11.4.nar-unpacked/NAR-INF/bundled-dependencies/jython-shaded-2.7.1.1.jar/Lib/site.py\\\", line 585, in <module>\\n  File \\\"/opt/nifi/nifi-current/work/nar/extensions/nifi-scripting-nar-1.11.4.nar-unpacked/NAR-INF/bundled-dependencies/jython-shaded-2.7.1.1.jar/Lib/site.py\\\", line 567, in main\\n  File \\\"/opt/nifi/nifi-current/work/nar/extensions/nifi-scripting-nar-1.11.4.nar-unpacked/NAR-INF/bundled-dependencies/jython-shaded-2.7.1.1.jar/Lib/site.py\\\", line 300, in addusersitepackages\\n  File \\\"/opt/nifi/nifi-current/work/nar/extensions/nifi-scripting-nar-1.11.4.nar-unpacked/NAR-INF/bundled-dependencies/jython-shaded-2.7.1.1.jar/Lib/site.py\\\", line 275, in getusersitepackages\\n  File \\\"/opt/nifi/nifi-current/work/nar/extensions/nifi-scripting-nar-1.11.4.nar-unpacked/NAR-INF/bundled-dependencies/jython-shaded-2.7.1.1.jar/Lib/site.py\\\", line 265, in getuserbase\\n  File \\\"/opt/nifi/nifi-current/work/nar/extensions/nifi-scripting-nar-1.11.4.nar-unpacked/NAR-INF/bundled-dependencies/jython-shaded-2.7.1.1.jar/Lib/sysconfig.py\\\", line 565, in get_config_var\\n  File \\\"/opt/nifi/nifi-current/work/nar/extensions/nifi-scripting-nar-1.11.4.nar-unpacked/NAR-INF/bundled-dependencies/jython-shaded-2.7.1.1.jar/Lib/sysconfig.py\\\", line 441, in get_config_vars\\n  File \\\"/opt/nifi/nifi-current/work/nar/extensions/nifi-scripting-nar-1.11.4.nar-unpacked/NAR-INF/bundled-dependencies/jython-shaded-2.7.1.1.jar/Lib/re.py\\\", line 106, in <module>\\nIOError: java.nio.channels.ClosedByInterruptException\\n: Traceback (most recent call last):\\n  File \\\"/opt/nifi/nifi-current/work/nar/extensions/nifi-scripting-nar-1.11.4.nar-unpacked/NAR-INF/bundled-dependencies/jython-shaded-2.7.1.1.jar/Lib/site.py\\\", line 585, in <module>\\n  File \\\"/opt/nifi/nifi-current/work/nar/extensions/nifi-scripting-nar-1.11.4.nar-unpacked/NAR-INF/bundled-dependencies/jython-shaded-2.7.1.1.jar/Lib/site.py\\\", line 567, in main\\n  File \\\"/opt/nifi/nifi-current/work/nar/extensions/nifi-scripting-nar-1.11.4.nar-unpacked/NAR-INF/bundled-dependencies/jython-shaded-2.7.1.1.jar/Lib/site.py\\\", line 300, in addusersitepackages\\n  File \\\"/opt/nifi/nifi-current/work/nar/extensions/nifi-scripting-nar-1.11.4.nar-unpacked/NAR-INF/bundled-dependencies/jython-shaded-2.7.1.1.jar/Lib/site.py\\\", line 275, in getusersitepackages\\n  File \\\"/opt/nifi/nifi-current/work/nar/extensions/nifi-scripting-nar-1.11.4.nar-unpacked/NAR-INF/bundled-dependencies/jython-shaded-2.7.1.1.jar/Lib/site.py\\\", line 265, in getuserbase\\n  File \\\"/opt/nifi/nifi-current/work/nar/extensions/nifi-scripting-nar-1.11.4.nar-unpacked/NAR-INF/bundled-dependencies/jython-shaded-2.7.1.1.jar/Lib/sysconfig.py\\\", line 565, in get_config_var\\n  File \\\"/opt/nifi/nifi-current/work/nar/extensions/nifi-scripting-nar-1.11.4.nar-unpacked/NAR-INF/bundled-dependencies/jython-shaded-2.7.1.1.jar/Lib/sysconfig.py\\\", line 441, in get_config_vars\\n  File \\\"/opt/nifi/nifi-current/work/nar/extensions/nifi-scripting-nar-1.11.4.nar-unpacked/NAR-INF/bundled-dependencies/jython-shaded-2.7.1.1.jar/Lib/re.py\\\", line 106, in <module>\\nIOError: java.nio.channels.ClosedByInterruptException\\n\", \"timestamp\": \"06:40:40 UTC\"}, {\"id\": 64755, \"category\": \"Log Message\", \"groupId\": \"4f68617e-e434-3774-cea6-47ce0a631fbe\", \"sourceId\": \"d135e6be-1f63-3651-ca5f-baf98d744a4d\", \"sourceName\": \"Add Labels\", \"level\": \"ERROR\", \"message\": \"ExecuteScript[id=d135e6be-1f63-3651-ca5f-baf98d744a4d] Failed to properly initialize Processor. If still scheduled to run, NiFi will attempt to initialize and run the Processor again after the 'Administrative Yield Duration' has elapsed. Failure is due to Traceback (most recent call last):\\n  File \\\"/opt/nifi/nifi-current/work/nar/extensions/nifi-scripting-nar-1.11.4.nar-unpacked/NAR-INF/bundled-dependencies/jython-shaded-2.7.1.1.jar/Lib/site.py\\\", line 68, in <module>\\n  File \\\"/opt/nifi/nifi-current/work/nar/extensions/nifi-scripting-nar-1.11.4.nar-unpacked/NAR-INF/bundled-dependencies/jython-shaded-2.7.1.1.jar/Lib/os.py\\\", line 50, in <module>\\n  File \\\"/opt/nifi/nifi-current/work/nar/extensions/nifi-scripting-nar-1.11.4.nar-unpacked/NAR-INF/bundled-dependencies/jython-shaded-2.7.1.1.jar/Lib/posixpath.py\\\", line 15, in <module>\\nIOError: java.nio.channels.ClosedByInterruptException\\n: Traceback (most recent call last):\\n  File \\\"/opt/nifi/nifi-current/work/nar/extensions/nifi-scripting-nar-1.11.4.nar-unpacked/NAR-INF/bundled-dependencies/jython-shaded-2.7.1.1.jar/Lib/site.py\\\", line 68, in <module>\\n  File \\\"/opt/nifi/nifi-current/work/nar/extensions/nifi-scripting-nar-1.11.4.nar-unpacked/NAR-INF/bundled-dependencies/jython-shaded-2.7.1.1.jar/Lib/os.py\\\", line 50, in <module>\\n  File \\\"/opt/nifi/nifi-current/work/nar/extensions/nifi-scripting-nar-1.11.4.nar-unpacked/NAR-INF/bundled-dependencies/jython-shaded-2.7.1.1.jar/Lib/posixpath.py\\\", line 15, in <module>\\nIOError: java.nio.channels.ClosedByInterruptException\\n\", \"timestamp\": \"06:39:11 UTC\"}, {\"id\": 64753, \"category\": \"Log Message\", \"groupId\": \"4f68617e-e434-3774-cea6-47ce0a631fbe\", \"sourceId\": \"050cb960-16e7-3e13-9c9a-ba003887408b\", \"sourceName\": \"Format Geotypes\", \"level\": \"ERROR\", \"message\": \"ExecuteScript[id=050cb960-16e7-3e13-9c9a-ba003887408b] Failed to properly initialize Processor. If still scheduled to run, NiFi will attempt to initialize and run the Processor again after the 'Administrative Yield Duration' has elapsed. Failure is due to Traceback (most recent call last):\\n  File \\\"/opt/nifi/nifi-current/work/nar/extensions/nifi-scripting-nar-1.11.4.nar-unpacked/NAR-INF/bundled-dependencies/jython-shaded-2.7.1.1.jar/Lib/site.py\\\", line 585, in <module>\\n  File \\\"/opt/nifi/nifi-current/work/nar/extensions/nifi-scripting-nar-1.11.4.nar-unpacked/NAR-INF/bundled-dependencies/jython-shaded-2.7.1.1.jar/Lib/site.py\\\", line 567, in main\\n  File \\\"/opt/nifi/nifi-current/work/nar/extensions/nifi-scripting-nar-1.11.4.nar-unpacked/NAR-INF/bundled-dependencies/jython-shaded-2.7.1.1.jar/Lib/site.py\\\", line 300, in addusersitepackages\\n  File \\\"/opt/nifi/nifi-current/work/nar/extensions/nifi-scripting-nar-1.11.4.nar-unpacked/NAR-INF/bundled-dependencies/jython-shaded-2.7.1.1.jar/Lib/site.py\\\", line 275, in getusersitepackages\\n  File \\\"/opt/nifi/nifi-current/work/nar/extensions/nifi-scripting-nar-1.11.4.nar-unpacked/NAR-INF/bundled-dependencies/jython-shaded-2.7.1.1.jar/Lib/site.py\\\", line 265, in getuserbase\\n  File \\\"/opt/nifi/nifi-current/work/nar/extensions/nifi-scripting-nar-1.11.4.nar-unpacked/NAR-INF/bundled-dependencies/jython-shaded-2.7.1.1.jar/Lib/sysconfig.py\\\", line 565, in get_config_var\\n  File \\\"/opt/nifi/nifi-current/work/nar/extensions/nifi-scripting-nar-1.11.4.nar-unpacked/NAR-INF/bundled-dependencies/jython-shaded-2.7.1.1.jar/Lib/sysconfig.py\\\", line 441, in get_config_vars\\n  File \\\"/opt/nifi/nifi-current/work/nar/extensions/nifi-scripting-nar-1.11.4.nar-unpacked/NAR-INF/bundled-dependencies/jython-shaded-2.7.1.1.jar/Lib/re.py\\\", line 280, in <module>\\nIOError: java.nio.channels.ClosedByInterruptException\\n: Traceback (most recent call last):\\n  File \\\"/opt/nifi/nifi-current/work/nar/extensions/nifi-scripting-nar-1.11.4.nar-unpacked/NAR-INF/bundled-dependencies/jython-shaded-2.7.1.1.jar/Lib/site.py\\\", line 585, in <module>\\n  File \\\"/opt/nifi/nifi-current/work/nar/extensions/nifi-scripting-nar-1.11.4.nar-unpacked/NAR-INF/bundled-dependencies/jython-shaded-2.7.1.1.jar/Lib/site.py\\\", line 567, in main\\n  File \\\"/opt/nifi/nifi-current/work/nar/extensions/nifi-scripting-nar-1.11.4.nar-unpacked/NAR-INF/bundled-dependencies/jython-shaded-2.7.1.1.jar/Lib/site.py\\\", line 300, in addusersitepackages\\n  File \\\"/opt/nifi/nifi-current/work/nar/extensions/nifi-scripting-nar-1.11.4.nar-unpacked/NAR-INF/bundled-dependencies/jython-shaded-2.7.1.1.jar/Lib/site.py\\\", line 275, in getusersitepackages\\n  File \\\"/opt/nifi/nifi-current/work/nar/extensions/nifi-scripting-nar-1.11.4.nar-unpacked/NAR-INF/bundled-dependencies/jython-shaded-2.7.1.1.jar/Lib/site.py\\\", line 265, in getuserbase\\n  File \\\"/opt/nifi/nifi-current/work/nar/extensions/nifi-scripting-nar-1.11.4.nar-unpacked/NAR-INF/bundled-dependencies/jython-shaded-2.7.1.1.jar/Lib/sysconfig.py\\\", line 565, in get_config_var\\n  File \\\"/opt/nifi/nifi-current/work/nar/extensions/nifi-scripting-nar-1.11.4.nar-unpacked/NAR-INF/bundled-dependencies/jython-shaded-2.7.1.1.jar/Lib/sysconfig.py\\\", line 441, in get_config_vars\\n  File \\\"/opt/nifi/nifi-current/work/nar/extensions/nifi-scripting-nar-1.11.4.nar-unpacked/NAR-INF/bundled-dependencies/jython-shaded-2.7.1.1.jar/Lib/re.py\\\", line 280, in <module>\\nIOError: java.nio.channels.ClosedByInterruptException\\n\", \"timestamp\": \"06:39:11 UTC\"}]}", "module": "main", "name": "__main__", "process": {"id": 18460, "name": "MainProcess"}, "thread": {"id": 140163409274688, "name": "MainThread"}, "time": {"repr": "2020-12-29 09:41:21.438118+03:00", "timestamp": 1609224081.438118}}}
{"text": "2020-12-29T09:41:21.440048+0300 INFO\n", "record": {"elapsed": {"repr": "0:00:01.565218", "seconds": 1.565218}, "exception": null, "extra": {}, "file": {"name": "main.py", "path": "main.py"}, "function": "process_nifi_connectors", "level": {"icon": "\u2139\ufe0f", "name": "INFO", "no": 20}, "line": 172, "message": "{\"id\": \"47551e5f-1787-1e9a-f7b8-a972e135f5a5\", \"name\": \"Unicef Angola\", \"parentGroupId\": \"50bce21f-0171-1000-d983-307ac9814c13\", \"runningCount\": 216, \"stoppedCount\": 42, \"invalidCount\": 30, \"disabledCount\": 0, \"activeRemotePortCount\": 0, \"inactiveRemotePortCount\": 0, \"upToDateCount\": 0, \"locallyModifiedCount\": 3, \"staleCount\": 0, \"locallyModifiedAndStaleCount\": 0, \"syncFailureCount\": 0, \"localInputPortCount\": 0, \"localOutputPortCount\": 0, \"publicInputPortCount\": 0, \"publicOutputPortCount\": 0, \"inputPortCount\": 0, \"outputPortCount\": 0, \"statsLastRefreshed\": \"06:41:21 UTC\", \"versionedFlowState\": null, \"flowFilesIn\": 0, \"bytesIn\": 0, \"input\": \"0 (0 bytes)\", \"flowFilesQueued\": 3401, \"bytesQueued\": 274, \"queued\": \"3,401 (274 bytes)\", \"queuedCount\": \"3,401\", \"queuedSize\": \"274 bytes\", \"bytesRead\": 187, \"read\": \"187 bytes\", \"bytesWritten\": 357303, \"written\": \"348.93 KB\", \"flowFilesOut\": 0, \"bytesOut\": 0, \"output\": \"0 (0 bytes)\", \"flowFilesTransferred\": 1729, \"bytesTransferred\": 666, \"transferred\": \"1,729 (666 bytes)\", \"bytesReceived\": 61, \"flowFilesReceived\": 1, \"received\": \"1 (61 bytes)\", \"bytesSent\": 0, \"flowFilesSent\": 0, \"sent\": \"0 (0 bytes)\", \"activeThreadCount\": 0, \"terminatedThreadCount\": 0, \"bulletinCount\": 5, \"errorCount\": 5, \"bulletins\": [{\"id\": 64965, \"category\": \"Log Message\", \"groupId\": \"57b13351-cc5e-181d-fdc5-a8460eb51ff6\", \"sourceId\": \"57b13360-cc5e-181d-2153-759e861a6efc\", \"sourceName\": \"UpdateAttribute\", \"level\": \"ERROR\", \"message\": \"UpdateAttribute[id=57b13360-cc5e-181d-2153-759e861a6efc] Failed to process session due to Unable to evaluate new value for attribute 'mother_id': org.apache.nifi.attribute.expression.language.exception.AttributeExpressionLanguageException: Subject is empty.: org.apache.nifi.processor.exception.ProcessException: Unable to evaluate new value for attribute 'mother_id': org.apache.nifi.attribute.expression.language.exception.AttributeExpressionLanguageException: Subject is empty.\", \"timestamp\": \"06:41:12 UTC\"}, {\"id\": 64964, \"category\": \"Log Message\", \"groupId\": \"57b13351-cc5e-181d-fdc5-a8460eb51ff6\", \"sourceId\": \"57b13360-cc5e-181d-2153-759e861a6efc\", \"sourceName\": \"UpdateAttribute\", \"level\": \"ERROR\", \"message\": \"UpdateAttribute[id=57b13360-cc5e-181d-2153-759e861a6efc] Could not evaluate the FlowFile 'StandardFlowFileRecord[uuid=86751ec9-1d7e-475d-b300-e8d4b2fe8e96,claim=StandardContentClaim [resourceClaim=StandardResourceClaim[id=1608216285625-2604, container=repo0, section=556], offset=4257783, length=2],offset=0,name=1f9018f2-5469-479a-b24d-58288ca0c628,size=2]' against expression '${relationships:jsonPath('$.mother[0]')}' defined by DynamicProperty 'mother_id' due to 'Subject is empty'\", \"timestamp\": \"06:41:12 UTC\"}, {\"id\": 64963, \"category\": \"Log Message\", \"groupId\": \"57b13351-cc5e-181d-fdc5-a8460eb51ff6\", \"sourceId\": \"57b13360-cc5e-181d-2153-759e861a6efc\", \"sourceName\": \"UpdateAttribute\", \"level\": \"ERROR\", \"message\": \"UpdateAttribute[id=57b13360-cc5e-181d-2153-759e861a6efc] Failed to process session due to Unable to evaluate new value for attribute 'mother_id': org.apache.nifi.attribute.expression.language.exception.AttributeExpressionLanguageException: Subject is empty.: org.apache.nifi.processor.exception.ProcessException: Unable to evaluate new value for attribute 'mother_id': org.apache.nifi.attribute.expression.language.exception.AttributeExpressionLanguageException: Subject is empty.\", \"timestamp\": \"06:41:12 UTC\"}, {\"id\": 64962, \"category\": \"Log Message\", \"groupId\": \"57b13351-cc5e-181d-fdc5-a8460eb51ff6\", \"sourceId\": \"57b13360-cc5e-181d-2153-759e861a6efc\", \"sourceName\": \"UpdateAttribute\", \"level\": \"ERROR\", \"message\": \"UpdateAttribute[id=57b13360-cc5e-181d-2153-759e861a6efc] Could not evaluate the FlowFile 'StandardFlowFileRecord[uuid=726f90b5-b451-4b07-8dbb-9c66a0907522,claim=StandardContentClaim [resourceClaim=StandardResourceClaim[id=1608216285625-2604, container=repo0, section=556], offset=4257266, length=2],offset=0,name=ae8ac1c2-f94b-4f30-a5d8-33674edbca8a,size=2]' against expression '${relationships:jsonPath('$.mother[0]')}' defined by DynamicProperty 'mother_id' due to 'Subject is empty'\", \"timestamp\": \"06:41:12 UTC\"}, {\"id\": 64961, \"category\": \"Log Message\", \"groupId\": \"57b13351-cc5e-181d-fdc5-a8460eb51ff6\", \"sourceId\": \"57b13360-cc5e-181d-2153-759e861a6efc\", \"sourceName\": \"UpdateAttribute\", \"level\": \"ERROR\", \"message\": \"UpdateAttribute[id=57b13360-cc5e-181d-2153-759e861a6efc] Failed to process session due to Unable to evaluate new value for attribute 'mother_id': org.apache.nifi.attribute.expression.language.exception.AttributeExpressionLanguageException: Subject is empty.: org.apache.nifi.processor.exception.ProcessException: Unable to evaluate new value for attribute 'mother_id': org.apache.nifi.attribute.expression.language.exception.AttributeExpressionLanguageException: Subject is empty.\", \"timestamp\": \"06:41:11 UTC\"}]}", "module": "main", "name": "__main__", "process": {"id": 18460, "name": "MainProcess"}, "thread": {"id": 140163409274688, "name": "MainThread"}, "time": {"repr": "2020-12-29 09:41:21.440048+03:00", "timestamp": 1609224081.440048}}}
{"text": "2020-12-29T09:41:21.440771+0300 INFO\n", "record": {"elapsed": {"repr": "0:00:01.565941", "seconds": 1.565941}, "exception": null, "extra": {}, "file": {"name": "main.py", "path": "main.py"}, "function": "process_nifi_connectors", "level": {"icon": "\u2139\ufe0f", "name": "INFO", "no": 20}, "line": 172, "message": "{\"id\": \"53fa72da-0171-1000-c0f9-48a8cdd9b8f3\", \"name\": \"IHME COVID-19 API Downloader\", \"parentGroupId\": \"50bce21f-0171-1000-d983-307ac9814c13\", \"runningCount\": 0, \"stoppedCount\": 13, \"invalidCount\": 6, \"disabledCount\": 0, \"activeRemotePortCount\": 0, \"inactiveRemotePortCount\": 0, \"upToDateCount\": 0, \"locallyModifiedCount\": 0, \"staleCount\": 0, \"locallyModifiedAndStaleCount\": 0, \"syncFailureCount\": 0, \"localInputPortCount\": 0, \"localOutputPortCount\": 0, \"publicInputPortCount\": 0, \"publicOutputPortCount\": 0, \"inputPortCount\": 0, \"outputPortCount\": 0, \"statsLastRefreshed\": \"06:41:21 UTC\", \"versionedFlowState\": \"UP_TO_DATE\", \"flowFilesIn\": 0, \"bytesIn\": 0, \"input\": \"0 (0 bytes)\", \"flowFilesQueued\": 0, \"bytesQueued\": 0, \"queued\": \"0 (0 bytes)\", \"queuedCount\": \"0\", \"queuedSize\": \"0 bytes\", \"bytesRead\": 0, \"read\": \"0 bytes\", \"bytesWritten\": 0, \"written\": \"0 bytes\", \"flowFilesOut\": 0, \"bytesOut\": 0, \"output\": \"0 (0 bytes)\", \"flowFilesTransferred\": 0, \"bytesTransferred\": 0, \"transferred\": \"0 (0 bytes)\", \"bytesReceived\": 0, \"flowFilesReceived\": 0, \"received\": \"0 (0 bytes)\", \"bytesSent\": 0, \"flowFilesSent\": 0, \"sent\": \"0 (0 bytes)\", \"activeThreadCount\": 0, \"terminatedThreadCount\": 0, \"bulletinCount\": 0, \"errorCount\": 0, \"bulletins\": []}", "module": "main", "name": "__main__", "process": {"id": 18460, "name": "MainProcess"}, "thread": {"id": 140163409274688, "name": "MainThread"}, "time": {"repr": "2020-12-29 09:41:21.440771+03:00", "timestamp": 1609224081.440771}}}
